# Site settings
title      : Boba Fett's resume #title of the resume - for browser
email      : boba@deathstar.gal # your email 
description: # Not used
baseurl    : "" # Github subfolder for project . If is your main git or you use a CNAME put ""
url        : "http://bobafett.leoderbois.com"  # Url of your site 


metadata: ["Leo Derbois","github","jekyll","jekyllrb","resume","CV","Boba Fett"] # Metadata for 
# If you want to analyse your site  with google analytics (code like UA-5293-1)
googleAnalyticsID: UA-54776487-1
#custom-css: /css/leoderbois.css # CSS with import main.less or not, to customise or override some properties


#### SEO Informations ####
SEO_GOOGLE_PUBLISHER: +LÃ©oDerbois #+YourName
SEO_LOCAL: en_US
#SEO_Title <- title
#SEO_DESCRIPTION  <- summary
#SEO_URL <- site.url
#SEO_site_name <-title
SEO_IMAGE: /assets/bobafett.jpg
SEO_ALEXA_VERIFY_ID: 
SEO_GOOGLE_SITE_VERIFICATION:

############################# Personnal Inforamtions ################################
name   : Boba Fett #Your name
summary: Intergalactic Hit Man # a simple sentence about you
quote  : "killing and kidnaping people is all my life. My father selected me because I was the best of a million of sons. I was made and educated to kill, kidnap and guard your body like nobody can do !" # a quote about you
phone  : +33 06 71 82 84 56 # your phone number

# Where you leave ?
street : 45 Wookies street
city   : Kamino			
zipcode: 45002				


# if you have a site or a custom blog
blog_name: Boba Fett At School 
blog_url : http://www.osxbricks.com

# your social informations
linkedin: bobafett # linkedin username
google  : bobafett # google username
github  : bobafett # github username
twitter : bobafett # twitter username
facebook: bobafett # facebook username


############################# Site Options ################################
favicon         : /assets/bobafett.ico 		# website Favicon  / Need to be local (in assets forlder)
#avatar          : NOW IN BOBAFETT.less
#panel_background: NOW IN BOBAFETT.less
enable_ribbon   : yes 						# remove this line to remove the github ribbon 


##### Custom category #####
custom_category_name: Custom Category # remove to disable custom cateogry. Markdown file need to get -> categories: customs.
custom_category_icon: bullhorn # fontawesom icon
############################ Resume Content ################################
# Your Hobbies
#if you remove this, articles with 'hobbies' category are considerated
hobbies: 
- Pod Racer Competition
- Computer Sciences
- Women
- Cooking for friends


# Your Kills
#if you remove this, articles with 'skills' category are considerated
skills:
 - sectionName: Hitman skills
   elements:
    - name: Weapons
      values: ["Blasters","Heavy ranged","Melee"]
    - name: Spacecraft
      values: ["Slave I & II","A-WING FIGHTER","AAT BATTLE TANK"]
    - name: Cooking
      values: ["Cake","Muffins"]
 - sectionName: Typist skills
   elements:
    - name: Microsoft Office
      values: ["Word","Excel","Powerpoint"]
    - name: Apple iWork
      values: ["Pages","Numbers"]

# Some inforamtions you want to add
informations-custom:
- text: Space ship drive Licence + vehicle
  logo: space-shuttle #fontawesome
- text: Cooking Wookie stuff
  logo: spoon #fontawesome
- text: Have a lot of guns

# Languages you speak (put your level in parentheses)
speaking-langugages: ["Mandalorian (native)","Huttese (professionnal)","Wookie (bases)"]

# a link to your PDF version of the remuse. If you remove, the button will disappear. 
resume_pdf: http://cl.ly/3c3a3F2v0a0v/download/boba_fett.pdf


############################# Build setting (don't touch!) ################################
markdown: kramdown
permalink: pretty

############################# Plugins ################################

# No plugin
